server:
  port: 80

spring:
  devtools:
    restart:
      enabled: true
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 30
        max-wait: 600
        max-idle: 5
        min-idle: 0
    timeout: 0
